name: Golang CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

jobs:
  go-build:
    name: Golang Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      # 依存モジュールのダウンロード
      - name: Download Go modules
        run: go mod download

      # プロジェクト全体のビルド
      - name: Build all
        run: go build ./...

  test:
    name: Golang Test
    runs-on: ubuntu-latest
    # ビルドが成功した場合にのみテストを実行
    needs: [build]
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      # テストの実行
      - name: Run tests
        run: go test -v ./...
