name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"
      - "hotfix/**"
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "modules/**"
      - "terraform/.tflint.hcl"
      - ".github/workflows/terraform.yaml"

permissions:
  contents: read

jobs:
  ci:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 初期化
      - name: Terraform init
        run: terraform init -backend=false -input=false

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          cache: true

      - name: TFLint init (install plugins)
        run: tflint --init
        env:
          # GitHub API レート制限を回避するためにトークンを設定
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      # セキュリティスキャン
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: config
          scan-ref: .
          hide-progress: true
          ignore-unfixed: true
          severity: "CRITICAL,HIGH,MEDIUM"
          exit-code: "1"
